### PR TITLE
Advance version to 1.2.0-SNAPSHOT, standardize maven plugin versions, switch scopes

### PR DESCRIPTION
**Pull request by floverfelt**
Fixes for issues #10 #8, advance version to prepare for release.

### CODE REVIEW

**Comment by hazendaz** [comment]
@floverfelt What is the status here?  With new issue popping its important to release and seems https://github.com/xdev-software/find-and-replace-maven-plugin may be forking ahead.  Maybe we can get things resolved before this gets fragmented ?

**Comment by floverfelt** [comment]
> @floverfelt What is the status here? With new issue popping its important to release and seems https://github.com/xdev-software/find-and-replace-maven-plugin may be forking ahead. Maybe we can get things resolved before this gets fragmented ?

I don't use this plugin day-to-day any longer and as such, I haven't been able to keep up with it at the same pace as when I originally wrote it. I can merge this and re-release today or I'm happy to archive this project and redirect people to the xdev fork if @AB-xdev wants to commit to maintaining it.

**Comment by hazendaz** [comment]
Hi @floverfelt Maybe a combination of both might work.  If you are to add commons-lang3 directly so maven 3.9.8 works plus this PR, it would solve concerns for now.  Test against maven 3.9.8 then to see before / after.  If not added, maven 3.9.8 will promptly through an error.

```
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.14.0</version>
</dependency>
```

**Comment by AB-xdev** [comment]
> I'm happy to archive this project and redirect people to the xdev fork if @AB-xdev wants to commit to maintaining it.

I stated our current position in https://github.com/xdev-software/find-and-replace-maven-plugin/issues/45.<br/>
If that suits you, feel free to redirect your plugin to ours :)

**Pull request merged**
